import { Metadata } from "next";
import React from "react";
export const metadata: Metadata = {
    title: "Privacy policy",
    description: "Generated by create next app",
  };

export default function Layout({ children }: Readonly<{
    children: React.ReactNode;
  }>) {
  return (
    <div className="min-h-screen w-full">
      <main className="m-5">{children}</main>
    </div>
  );
}
